[colors.primary]
background = '#16161e'
foreground = '#e0cca8'

[colors.selection]
text = '#e0cca8'
background = '#7dcfff'

[colors.cursor]
text = '#16161e'
cursor = '#8a9887'

[colors.normal]
black   = '#1a1b26'
red     = '#be715b'
green   = '#4e984c'
yellow  = '#beb155'
blue    = '#80907d'
magenta = '#3a4637'
cyan    = '#8a9887'
white   = '#979f96'

[colors.bright]
black   = '#777e76'
red     = '#cd9180'
green   = '#78b676'
yellow  = '#e3da94'
blue    = '#9aa797'
magenta = '#b8c5b6'
cyan    = '#cbd4ca'
white   = '#d7dcd6'
