[colors.primary]
background = '#16161e'
foreground = '#e0cca8'
 
[colors.cursor]
text = '#e0cca8'
cursor = '#b694b6' 
 
[colors.vi_mode_cursor]
text = '#16161e'
cursor = '#8a9887' 
 
[colors.search.matches]
foreground = '#242729' 
background = '#8a9887' 
 
[colors.search.focused_match]
foreground = '#242729' 
background = '#8a9887' 
 
[colors.footer_bar]
foreground = '#242729' 
background = '#e1e2e7' 
 
[colors.hints.start]
foreground = '#242729' 
background = '#8a9887' 
 
[colors.hints.end]
foreground = '#242729' 
background = '#8a9887' 
 
[colors.selection]
text = '#16161e'
background = '#8a9887'
 
 
[colors.normal]
black = '#181818' 
red = '#a8721b' 
green = '#8a9887' 
yellow = '#8a9887' 
blue = '#8a9887' 
magenta = '#8a9887' 
cyan = '#8a9887' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
